version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - ./backend/.env
    ports:
      - "5001:10000"       # host:container
    volumes:
      - ./backend/chroma:/app/chroma                  # persists your vectorstore
      - ./backend/knowledge_base:/app/knowledge_base:ro  # read-only mount for MDs
    command: >
      gunicorn flask_app:app
        --workers 1
        --worker-class sync
        --bind 0.0.0.0:10000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: npm run start
